### ISSUE TITLE
Post-installer issues

### ISSUE THREAD

**Issue by i3-Arch** [i3-Arch/Arch-Installer#8]
Tested with i686 install and "bobthebuilder" function seems to have not successfully installed pacaur

**Comment by t60r** [comment]
This has to do with the PGP key most likely, pacaurs makepkg doesnt seem to
pull the correct key...this should be able to be remedied using the gpg
recv-keys key-id command somewhere in the function.  If I have time, I'll
take a look at it.  Also...what's good man?  It's been a grip!  Shoot me an
email, we need to catch up.

**Comment by i3-Arch** [comment]
Whats up bro!  Yeah, Ive not talked to dtf in forever also. His teamspeak
server is down.

the teamspeak server you can catch me on is ts3.rootd.it


Here is my latest little project

http://archstuff.tk

**Comment by t60r** [comment]
Cool website, nice century link. :3

Yeah, looks like the entire ts vanished into thin air.  I'll stop in to
rootd though and try to catch ya though.  I was just in a minute ago they
seem legit...are they all gamers or something?  Anyhow...I'll try to see ya
on there, it's been too long mang.

**Comment by i3-Arch** [comment]
Problem was unmet dependencies ( missing packages `git ` and `perl-error`)

They could not be installed because `makepkg -s` was being run as a user via `su "$user" -c "cmd"`.
